a=list(input().split())
a[1]=int(a[1])
mytuple1=tuple(a)
b=list(input().split())
b[1]=int(b[1])
mytuple2=tuple(b)
print("Tuple 1: ",mytuple1)
print("Tuple 2: ",mytuple2)
print("Tuple 1 and Tuple 2 is ",mytuple1+mytuple2)